name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
#     - name: Create Zip File
#       uses: montudor/action-zip@v0.1.0
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Extension Build
        # Directory containing files to upload
        path: ./dist
